version: '3'

services:

  ##
  elastic:
    image: fogfish/elasticsearch:6.2.3
    ports:
      - 9200:9200

  ##
  proxy42:
    build:
      context: . 
    ports:
      - 4001:4001
      - 8080:8080
