swagger: '2.0'
info:
  description: Proxy42 Administrative API
  version: 1.0.0
  title: Proxy42 Admin API
  contact:
    email: info@apinf.io

  license:
    name: EUPL 1.1
    url: https://opensource.org/licenses/EUPL-1.1

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls

paths:
  /apis:
    get:
      tags:
      - admins
      summary: get a list of all managed APIs
      operationId: getAPIs
      description: |
        Get a list of all managed APIs
      produces:
      - application/json
      responses:
        200:
          description: a list of all managed APIs
          schema:
            type: array
            items:
              $ref: '#/definitions/API'
    post:
      tags:
      - admins
      summary: registers an API
      operationId: registerAPI
      description: registers a new API
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: API
        description: API parameters to be registered
        schema:
          $ref: '#/definitions/API'
      responses:
        201:
          description: API registered
        400:
          description: invalid input, object invalid
          
  /apis/{id}:
    get:
      tags:
      - admins
      summary: get existing API details
      operationId: getAPI
      description: |
        Get an existing API
      parameters:
      - name: id
        in: path
        description: ID of API to fetch
        required: true
        type: string
        format: uuid
      produces: 
      - application/json
      responses:
        200:
          description: existing API details
          schema:
            $ref: '#/definitions/API'
        
definitions:
  API:
    type: object
    required:
    - id
    - hostname
    - servers
    - frontend_prefix
    - backend_prefix
    - strategy
    - additional_headers
    - rate_limit
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      hostname:
        type: string
        example: "https://httpbin.org"
      servers:
        type: array
        items: 
          type: string
        example: ["https://httpbin.org", "10.3.100.207"]
      frontend_prefix:
        type: string
        example: "/v1/"
      backend_prefix:
        type: string
        example: "/v0/"
      strategy:
        type: string
        enum: ["random"]
      additional_headers:
        type: string
        example: ""
      rate_limit:
        type: integer
